
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-v1-hpa
  namespace: product-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-v1-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
